#server 端口号设置
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

#注册中心设置，server本身不被发现
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0